name: validate qupath collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BIOIMAGEIO_COUNT_RDF_DOWNLOADS: 'false'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install bioimageio.spec
      run: pip install bioimageio.spec lxml
    - name: validate collection
      run: bioimageio validate-partner-collection collection.yaml
